// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Admin_head: typeof import('./src/components/admin/admin_head.vue')['default']
    Admin_page: typeof import('./src/components/admin_page.vue')['default']
    Admin_title: typeof import('./src/components/admin/admin_title.vue')['default']
    Announcement_page: typeof import('./src/components/admin/system/announcement_page.vue')['default']
    Closing_page: typeof import('./src/components/admin/monitor/closing_page.vue')['default']
    Dictionary_page: typeof import('./src/components/admin/system/dictionary_page.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Environmental_page: typeof import('./src/components/admin/monitor/Environmental_page.vue')['default']
    Feeder_page: typeof import('./src/components/admin/monitor/feeder_page.vue')['default']
    Gateway_page: typeof import('./src/components/admin/monitor/gateway_page.vue')['default']
    Hall_page: typeof import('./src/components/admin/hall_page.vue')['default']
    Login_page: typeof import('./src/components/login_page.vue')['default']
    Maindiagram_page: typeof import('./src/components/admin/monitor/maindiagram_page.vue')['default']
    New_data: typeof import('./src/components/admin/monitor/new_data.vue')['default']
    Orginazation_page: typeof import('./src/components/admin/system/orginazation_page.vue')['default']
    Panorama_page: typeof import('./src/components/admin/panorama_page.vue')['default']
    Parameter_page: typeof import('./src/components/admin/system/parameter_page.vue')['default']
    Permissions_page: typeof import('./src/components/admin/system/Permissions_page.vue')['default']
    Post_page: typeof import('./src/components/admin/system/post_page.vue')['default']
    Resource_page: typeof import('./src/components/admin/system/resource_page.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Serve_page: typeof import('./src/components/admin/system/serve_page.vue')['default']
    Stations_page: typeof import('./src/components/admin/monitor/stations_page.vue')['default']
    Terminal_page: typeof import('./src/components/admin/monitor/terminal_page.vue')['default']
    Transformer_page: typeof import('./src/components/admin/monitor/transformer_page.vue')['default']
    User_page: typeof import('./src/components/admin/system/user_page.vue')['default']
  }
}
